language: ruby
dist: trusty
os:
  - linux
  - osx

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.8
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

  exclude:
    - os: osx
      rvm: 1.9.3
    - os: osx
      rvm: 2.0.0

    - os: osx
      rvm: 1.8.7

#  include:
#    - os: osx
#      rvm: 1.9.3
#      before_script: rvm install ruby-1.9.3 # not binary
#    - os: osx
#      rvm: 2.0.0
#      before_script: rvm install ruby-2.0.0 # not binary
